### ISSUE TITLE
Cannot kill Hugo Server | Also no notification when the server is initiated

### ISSUE THREAD

**Issue by onedrawingperday** [calintat/atom-hugo#2]
I installed `atom-hugo` successfully and I am able to create new posts in my Hugo project.

But when I go to `>Packages>Hugo>Server` nothing happens.

What am I missing? Shouldn't this command open the Hugo Server in a new browser window? Or is there an Atom dependency that I should have installed first?

I'm using the Atom snap on Ubuntu 16.04

**EDIT**
Looking at `atom-hugo.coffee` I discovered that Hugo Server is initiated at `http://localhost:2897/`

Don't know how was I supposed to know? There is no browser window opening or some kind of notification.

But the real problem is that I cannot kill Hugo Server with the command provided. Here is the error that Atom throws.

```

> Uncaught Error: kill EACCES
>     at exports._errnoException (util.js:1022:11)
>     at ChildProcess.kill (internal/child_process.js:392:26)
>     at Object.killServer (/home/alex/.atom/packages/atom-hugo/lib/atom-hugo.coffee:155:43)
>     at HTMLElement.subscriptions.add.atom.commands.add.atom-hugo:kill-server (/home/alex/.atom/packages/atom-hugo/lib/atom-hugo.coffee:80:36)
>     at CommandRegistry.handleCommandEvent (/snap/atom/76/usr/share/atom/resources/app/src/command-registry.js:381:36)
>     at CommandRegistry.dispatch (/snap/atom/76/usr/share/atom/resources/app/src/command-registry.js:266:23)
>     at AtomEnvironment.module.exports.AtomEnvironment.dispatchApplicationMenuCommand (/snap/atom/76/usr/share/atom/resources/app/src/atom-environment.js:1382:34)
>     at EventEmitter.outerCallback (/snap/atom/76/usr/share/atom/resources/app/src/application-delegate.js:335:31)
>     at emitThree (events.js:116:13)
>     at EventEmitter.emit (events.js:194:7)

```

**Comment by jare19** [comment]
Kill server works for me, unless I restart atom after a server has been spawned, then I have to kill the pid manually.
you can work around the server not killing by killing the pid manually.

I just PR'd #3 which fixes the browser opening the correct preview page.  Although, I cannot seem to get the live refresh working at the moment so you will need to launch the server again to see changes, but I am trying to work on a fix for that as well.
